### ISSUE TITLE
JSON Template

### ISSUE THREAD

**Issue by Kleinpenny** [Kleinpenny/VCTEVA#6]
```
{
    "111170217799167483": {
        "handle": "Starbound",
        "name": "David Waugh",
        "homeTeam": "109144832518501870",
        "selected_agents":{
            "707EAB51-4836-F488-046A-CDA6BF494859": 0
        },
        "region": "",
        "weapons":{
            "9C82E19D-4575-0200-1A81-3EACF00CF872": 0
        },
        "game-changers-2022": {
            "Jam":{
                "games_win": 0,
                "games_count": 0,
                "attack":{
                    "kill": 0,
                    "death": 0,
                    "assistence": 0,
                    "rounds_taken": 0,
                    "rounds_win": 0,
                    "damage_caused": {
                        "LEG_count": 0,
                        "LEG_amount": 0,
                        "BODY_count": 0,
                        "BODY_amount": 0,
                        "GENERAL_count": 0,
                        "GENERAL_amount": 0,
                        "HEAD_count": 0,
                        "HEAD_amount": 0
                    },
                    "damage_received": {
                        "LEG_count": 0,
                        "LEG_amount": 0,
                        "BODY_count": 0,
                        "BODY_amount": 0,
                        "GENERAL_count": 0,
                        "GENERAL_amount": 0,
                        "HEAD_count": 0,
                        "HEAD_amount": 0
                    }
                },
                "defend":{
                    "kill": 0,
                    "death": 0,
                    "assistence": 0,
                    "rounds_taken": 0,
                    "rounds_win": 0,
                    "damage_caused": {
                        "LEG_count": 0,
                        "LEG_amount": 0,
                        "BODY_count": 0,
                        "BODY_amount": 0,
                        "GENERAL_count": 0,
                        "GENERAL_amount": 0,
                        "HEAD_count": 0,
                        "HEAD_amount": 0
                    },
                    "damage_received": {
                        "LEG_count": 0,
                        "LEG_amount": 0,
                        "BODY_count": 0,
                        "BODY_amount": 0,
                        "GENERAL_count": 0,
                        "GENERAL_amount": 0,
                        "HEAD_count": 0,
                        "HEAD_amount": 0
                    }
                }
            }
        }
    }
}
```

**Comment by Kleinpenny** [comment]
```
"homeTeam": "109144832518501870", -> 最近服役的队伍
        "selected_agents":{
            "707EAB51-4836-F488-046A-CDA6BF494859": 0 -> {agent的guid : 选择过的数量}
        },
        "region": "", -> 最近服役的队伍所在的地区
        "weapons":{
            "9C82E19D-4575-0200-1A81-3EACF00CF872": 0 ->{weapon的guid: 选择过的数量}
        },
        "game-changers-2022": { -> LEAGUES-YEAR
                    "Jam":{ -> 选择的地图的名称作为key
```

**Comment by YoshikoNashi** [comment]
"configuration": {"teams": [{"teamId": {"value": 21}, "playersInTeam": [{"value": 6}, {"value": 7}, {"value": 8}, {"value": 9}, {"value": 10}], "name": "Red"}, {"teamId": {"value": 22}, "playersInTeam": [{"value": 1}, {"value": 2}, {"value": 3}, {"value": 4}, {"value": 5}], "name": "Blue"}], "selectedMap": {"id": "UNKNOWN", "fallback": {"guid": "/Game/Maps/Canyon/Canyon", "displayName": "Canyon"}
可以通过类似这样的字段找到地图，攻防手和队员id

**Comment by YoshikoNashi** [comment]
```
{
  "id": "108065567071390915",
  "acronym": "XSET",
  "home_league_id": "106976737954740691",
  "dark_logo_url": "http://static.lolesports.com/teams/1648949691769_XSETFE.png",
  "light_logo_url": "http://static.lolesports.com/teams/1648949691767_XSETFE.png",
  "slug": "xset-fe",
  "name": "XSET Purple"
},
```
```
{
  "id": "108065567071390915",
  "acronym": "XSET",
  "home_league_id": "106976737954740691",
  "dark_logo_url": "http://static.lolesports.com/teams/1648949691769_XSETFE.png",
  "light_logo_url": "http://static.lolesports.com/teams/1648949691767_XSETFE.png",
  "slug": "xset-fe",
  "name": "XSET Purple"
},
```
一个teamid也对应多个team，麻了

**Comment by YoshikoNashi** [comment]
`{"platformGameId": "val:fed63e04-ca7d-45c1-9df9-a173448359d1", "gameDecided": {"state": "WINNER_DECIDED", "winningTeam": {"value": 17}, "spikeMode": {"currentRound": 21, "attackingTeam": {"value": 17}, "completedRounds": [{"roundNumber": 1, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 2, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 3, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 4, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 5, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 6, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 7, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 8, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 9, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "TIME_EXPIRED", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 10, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "ELIMINATION", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 16}}, {"roundNumber": 11, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "SPIKE_DEFUSE", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 12, "spikeModeResult": {"attackingTeam": {"value": 16}, "cause": "SPIKE_DEFUSE", "defendingTeam": {"value": 17}}, "winningTeam": {"value": 17}}, {"roundNumber": 13, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 16}}, {"roundNumber": 14, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "SPIKE_DEFUSE", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 16}}, {"roundNumber": 15, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 16, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 17, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 18, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 19, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 20, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}, {"roundNumber": 21, "spikeModeResult": {"attackingTeam": {"value": 17}, "cause": "ELIMINATION", "defendingTeam": {"value": 16}}, "winningTeam": {"value": 17}}], "roundsToWin": 13, "defendingTeam": {"value": 16}}}, "metadata": {"serverInfo": {"processId": "", "rfc190Scope": "aresriot.aws-apse1-prod.tournament-gp-singapore-1.ares.gameserver"}, "playback": 0, "sequenceNumber": 7197, "stage": 1, "gameVersion": "05.06.00.765767", "gameId": {"value": "fed63e04-ca7d-45c1-9df9-a173448359d1"}, "eventTime": {"includedPauses": "3894.039s", "omittingPauses": "3894.039s"}, "wallTime": "2022-10-02T09:16:33.195Z"}}`

gameDecided， 每局只有一个次事件，代表整局游戏结束。
游戏规则是赢满13轮的队伍获胜。整局游戏使用一张地图不换图，前十三轮攻防不变，13轮后攻防互换。在赢满13轮后，依然会有一个roundstartd，但是没有roundend。
这个start的round可以当作结算轮去理解。
**在这个roundstart后可能依然会有一些交易记录等event，不应该考虑。**

**Comment by JohannHalley** [comment]
id
- handle（在游戏中，handle 通常指的是玩家的昵称或用户名。）
- name
- career
    -  vct-challengers (league)
        - 2022 (year)
            - game
                - gameId
                - teamId
                - Map
                - selectedAgent
                - type
                - displayName
                - tagLine
                - accountId
                - rounds
                    - round 1
                        - kda
                    - round 2
            - 
         - 2023 
             - xxxxxx 
     -  (league)
